// <auto-generated />
using System;
using Dotnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240720083919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dotnet.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "M001",
                            Name = "D001"
                        },
                        new
                        {
                            Id = 2,
                            Model = "M002",
                            Name = "D002"
                        },
                        new
                        {
                            Id = 3,
                            Model = "M003",
                            Name = "D003"
                        },
                        new
                        {
                            Id = 4,
                            Model = "M004",
                            Name = "D004"
                        },
                        new
                        {
                            Id = 5,
                            Model = "M005",
                            Name = "D005"
                        },
                        new
                        {
                            Id = 6,
                            Model = "M006",
                            Name = "D006"
                        },
                        new
                        {
                            Id = 7,
                            Model = "M007",
                            Name = "D007"
                        },
                        new
                        {
                            Id = 8,
                            Model = "M008",
                            Name = "D008"
                        },
                        new
                        {
                            Id = 9,
                            Model = "M009",
                            Name = "D009"
                        },
                        new
                        {
                            Id = 10,
                            Model = "M0010",
                            Name = "D0010"
                        });
                });

            modelBuilder.Entity("Dotnet.Models.EVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EVouchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10001",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1183)
                        },
                        new
                        {
                            Id = 2,
                            Code = "10002",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1257)
                        },
                        new
                        {
                            Id = 3,
                            Code = "10003",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1282)
                        },
                        new
                        {
                            Id = 4,
                            Code = "10004",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1304)
                        },
                        new
                        {
                            Id = 5,
                            Code = "10005",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1324)
                        },
                        new
                        {
                            Id = 6,
                            Code = "10006",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1347)
                        },
                        new
                        {
                            Id = 7,
                            Code = "10007",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1368)
                        },
                        new
                        {
                            Id = 8,
                            Code = "10008",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1387)
                        },
                        new
                        {
                            Id = 9,
                            Code = "10009",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1468)
                        },
                        new
                        {
                            Id = 10,
                            Code = "100010",
                            ExpiryDate = new DateTime(2024, 8, 19, 8, 39, 19, 18, DateTimeKind.Local).AddTicks(1491)
                        });
                });

            modelBuilder.Entity("Dotnet.Models.Simcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ICCID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMSI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SimCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ICCID = "ICCID001",
                            IMSI = "IMSI001"
                        },
                        new
                        {
                            Id = 2,
                            ICCID = "ICCID002",
                            IMSI = "IMSI002"
                        },
                        new
                        {
                            Id = 3,
                            ICCID = "ICCID003",
                            IMSI = "IMSI003"
                        },
                        new
                        {
                            Id = 4,
                            ICCID = "ICCID004",
                            IMSI = "IMSI004"
                        },
                        new
                        {
                            Id = 5,
                            ICCID = "ICCID005",
                            IMSI = "IMSI005"
                        },
                        new
                        {
                            Id = 6,
                            ICCID = "ICCID006",
                            IMSI = "IMSI006"
                        },
                        new
                        {
                            Id = 7,
                            ICCID = "ICCID007",
                            IMSI = "IMSI007"
                        },
                        new
                        {
                            Id = 8,
                            ICCID = "ICCID008",
                            IMSI = "IMSI008"
                        },
                        new
                        {
                            Id = 9,
                            ICCID = "ICCID009",
                            IMSI = "IMSI009"
                        },
                        new
                        {
                            Id = 10,
                            ICCID = "ICCID0010",
                            IMSI = "IMSI0010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
